# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d74704a19c85e431c9037be1aa33b7e02917c3e3a149b30bf47312012d4d91799013495cc78e3aec58497782f5696d56d9fc7daf3d297cbb9c31b5023a2099

test:
  secret_key_base: 6fa16d3d8d2119673f24207b20c04dc2a6de47729bbc558923486adc3ea393e60465c84a7ace8a4ca42ed522b6e3e45ac2e34588b4e512903eb53f6856d111c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
